import os
import argparse
import concurrent.futures
import socket
import fnmatch
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from tqdm import tqdm

SCOPES = ['https://www.googleapis.com/auth/drive']

def authenticate(client_secret_file, token_file, hostname, port):
    creds = None
    if os.path.exists(token_file):
        creds = Credentials.from_authorized_user_file(token_file, SCOPES)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(client_secret_file, SCOPES)
            try:
                # Test if port is open before letting the flow use it, to catch OSError
                with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                    s.bind(('0.0.0.0', port))  # bind to all interfaces to test availability
                # We pass the hostname here so the redirect_uri generated by the flow matches the host
                creds = flow.run_local_server(host=hostname, port=port)
            except OSError as e:
                raise RuntimeError(f"Could not bind to port {port}. Is it already in use?")
        
        with open(token_file, 'w') as token:
            token.write(creds.to_json())
    return creds

def get_or_create_folder(service, folder_name, parent_id):
    query = f"name='{folder_name}' and '{parent_id}' in parents and mimeType='application/vnd.google-apps.folder' and trashed=false"
    response = service.files().list(q=query, spaces='drive', fields='files(id, name)', supportsAllDrives=True, includeItemsFromAllDrives=True).execute()
    files = response.get('files', [])
    if files:
        return files[0]['id']
    else:
        file_metadata = {
            'name': folder_name,
            'parents': [parent_id],
            'mimeType': 'application/vnd.google-apps.folder'
        }
        folder = service.files().create(body=file_metadata, fields='id', supportsAllDrives=True).execute()
        return folder.get('id')

def ensure_drive_path(service, dest_path, root_folder_id):
    if not dest_path or dest_path == '.' or dest_path == '/':
        return root_folder_id
        
    parts = dest_path.strip('/').split('/')
    current_parent_id = root_folder_id
    for part in parts:
        if part:
            current_parent_id = get_or_create_folder(service, part, current_parent_id)
    return current_parent_id

def should_upload(rel_path, includes, excludes):
    rel_path = rel_path.replace('\\', '/')
    filename = os.path.basename(rel_path)
    
    for ex in excludes:
        # Handle rclone style **/.ipynb_checkpoints/**
        ex_clean = ex.replace('*', '').replace('/', '')
        if ex_clean and ex_clean in rel_path.split('/'):
            return False
        if fnmatch.fnmatch(filename, ex) or fnmatch.fnmatch(rel_path, ex):
            return False
            
    if includes:
        for inc in includes:
            if fnmatch.fnmatch(filename, inc) or fnmatch.fnmatch(rel_path, inc):
                return True
        return False
        
    return True

def upload_file(creds, local_path, drive_folder_id, show_progress, overall_progress):
    service = build('drive', 'v3', credentials=creds)
    filename = os.path.basename(local_path)
    
    query = f"name='{filename}' and '{drive_folder_id}' in parents and trashed=false"
    response = service.files().list(q=query, spaces='drive', fields='files(id)', supportsAllDrives=True, includeItemsFromAllDrives=True).execute()
    files = response.get('files', [])
    
    file_metadata = {'name': filename}
    if not files:
        file_metadata['parents'] = [drive_folder_id]
        
    media = MediaFileUpload(local_path, resumable=True, chunksize=1024*1024)
    if files:
        file_id = files[0]['id']
        request = service.files().update(fileId=file_id, media_body=media, supportsAllDrives=True)
    else:
        request = service.files().create(body=file_metadata, media_body=media, supportsAllDrives=True)

    file_size = os.path.getsize(local_path)
    
    pbar = None
    if show_progress:
        # Use leave=False to keep the terminal relatively clean
        pbar = tqdm(total=file_size, desc=f"Uploading {filename}", leave=False, unit='B', unit_scale=True)
    
    response = None
    while response is None:
        status, response = request.next_chunk()
        if status and pbar:
            pbar.n = status.resumable_progress
            pbar.refresh()
            
    if pbar:
        pbar.n = file_size
        pbar.refresh()
        pbar.close()
        
    if overall_progress:
        overall_progress.update(1)

def main():
    parser = argparse.ArgumentParser(description="Upload a directory to Google Drive.")
    parser.add_argument('--folder-id', required=True, help="Google Drive Root Folder ID")
    parser.add_argument('--source', required=True, help="Local source directory path")
    parser.add_argument('--dest', default='', help="Destination directory structure inside the Google Drive folder")
    parser.add_argument('--client-secret', default='credentials.json', help="Path to OAuth client secret JSON file")
    parser.add_argument('--token-file', default='token.json', help="Path to save the OAuth token")
    parser.add_argument('--hostname', default=socket.gethostname(), help="Hostname for the OAuth redirect URI")
    parser.add_argument('--port', type=int, default=8000, help="Port for the OAuth redirect URI")
    parser.add_argument('--exclude', action='append', default=[], help="Exclude files/directories matching this pattern (can be used multiple times)")
    parser.add_argument('--include', action='append', default=[], help="Include files matching this pattern (if specified, excludes all others)")
    parser.add_argument('--show-progress', action='store_true', help="Show upload progress bars")
    parser.add_argument('--workers', type=int, default=5, help="Number of parallel upload workers")
    
    args = parser.parse_args()
    
    if not os.path.exists(args.source):
        print(f"Error: Source directory '{args.source}' does not exist.")
        return
        
    if not os.path.exists(args.client_secret):
        print(f"Error: Client secret file '{args.client_secret}' not found.")
        return

    creds = authenticate(args.client_secret, args.token_file, args.hostname, args.port)
    # Service for initial folder creation (synchronous)
    service = build('drive', 'v3', credentials=creds)
    
    print(f"Scanning local directory: {args.source}")
    files_to_upload = []
    
    # Pre-compute all required directories to create them synchronously
    # Mapping of relative local dir -> Google Drive Folder ID
    dir_mapping = {}
    
    for root, dirs, files in os.walk(args.source):
        rel_dir = os.path.relpath(root, args.source)
        if rel_dir == '.':
            rel_dir = ''
            
        full_dest_path = os.path.join(args.dest, rel_dir).replace('\\', '/').strip('/')
        
        for f in files:
            local_path = os.path.join(root, f)
            rel_file_path = os.path.join(rel_dir, f).replace('\\', '/').strip('/')
            
            if should_upload(rel_file_path, args.include, args.exclude):
                files_to_upload.append({
                    'local_path': local_path,
                    'dest_dir_path': full_dest_path
                })
            
    if not files_to_upload:
        print("No files found to upload.")
        return
        
    print(f"Found {len(files_to_upload)} files. Resolving Drive folders...")
    
    # Get the unique destination directories
    unique_dest_dirs = set(f['dest_dir_path'] for f in files_to_upload)
    
    # Sort them so parents are created before children
    unique_dest_dirs = sorted(list(unique_dest_dirs))
    
    for dest_dir in unique_dest_dirs:
        folder_id = ensure_drive_path(service, dest_dir, args.folder_id)
        dir_mapping[dest_dir] = folder_id
        
    print("Folders resolved. Starting upload...")
    
    overall_progress = None
    if args.show_progress:
        overall_progress = tqdm(total=len(files_to_upload), desc="Overall Progress", unit="file", position=0)
        
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.workers) as executor:
        futures = []
        for file_info in files_to_upload:
            local_path = file_info['local_path']
            folder_id = dir_mapping[file_info['dest_dir_path']]
            futures.append(
                executor.submit(upload_file, creds, local_path, folder_id, args.show_progress, overall_progress)
            )
            
        for future in concurrent.futures.as_completed(futures):
            try:
                future.result()
            except Exception as e:
                print(f"\\nError uploading a file: {e}")
                
    if overall_progress:
        overall_progress.close()
        
    print("Upload complete!")

if __name__ == '__main__':
    main()
