// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/export.proto

package exportpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExportRequest_Metadata
	//	*ExportRequest_Batch
	Payload       isExportRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_proto_export_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_export_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_proto_export_proto_rawDescGZIP(), []int{0}
}

func (x *ExportRequest) GetPayload() isExportRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExportRequest) GetMetadata() *ExportMetadata {
	if x != nil {
		if x, ok := x.Payload.(*ExportRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *ExportRequest) GetBatch() *ExportBatch {
	if x != nil {
		if x, ok := x.Payload.(*ExportRequest_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

type isExportRequest_Payload interface {
	isExportRequest_Payload()
}

type ExportRequest_Metadata struct {
	Metadata *ExportMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type ExportRequest_Batch struct {
	Batch *ExportBatch `protobuf:"bytes,2,opt,name=batch,proto3,oneof"`
}

func (*ExportRequest_Metadata) isExportRequest_Payload() {}

func (*ExportRequest_Batch) isExportRequest_Payload() {}

type ExportMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExpectedLogbooks int64                  `protobuf:"varint,1,opt,name=expected_logbooks,json=expectedLogbooks,proto3" json:"expected_logbooks,omitempty"`
	ExpectedEntries  int64                  `protobuf:"varint,2,opt,name=expected_entries,json=expectedEntries,proto3" json:"expected_entries,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExportMetadata) Reset() {
	*x = ExportMetadata{}
	mi := &file_proto_export_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportMetadata) ProtoMessage() {}

func (x *ExportMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_export_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportMetadata.ProtoReflect.Descriptor instead.
func (*ExportMetadata) Descriptor() ([]byte, []int) {
	return file_proto_export_proto_rawDescGZIP(), []int{1}
}

func (x *ExportMetadata) GetExpectedLogbooks() int64 {
	if x != nil {
		return x.ExpectedLogbooks
	}
	return 0
}

func (x *ExportMetadata) GetExpectedEntries() int64 {
	if x != nil {
		return x.ExpectedEntries
	}
	return 0
}

type ExportBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logbooks      []*Logbook             `protobuf:"bytes,1,rep,name=logbooks,proto3" json:"logbooks,omitempty"`
	Entries       []*LogbookEntry        `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportBatch) Reset() {
	*x = ExportBatch{}
	mi := &file_proto_export_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportBatch) ProtoMessage() {}

func (x *ExportBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_export_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportBatch.ProtoReflect.Descriptor instead.
func (*ExportBatch) Descriptor() ([]byte, []int) {
	return file_proto_export_proto_rawDescGZIP(), []int{2}
}

func (x *ExportBatch) GetLogbooks() []*Logbook {
	if x != nil {
		return x.Logbooks
	}
	return nil
}

func (x *ExportBatch) GetEntries() []*LogbookEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_proto_export_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_export_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_proto_export_proto_rawDescGZIP(), []int{3}
}

func (x *ExportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Logbook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	LogbookId     string                 `protobuf:"bytes,2,opt,name=logbook_id,json=logbookId,proto3" json:"logbook_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logbook) Reset() {
	*x = Logbook{}
	mi := &file_proto_export_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logbook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logbook) ProtoMessage() {}

func (x *Logbook) ProtoReflect() protoreflect.Message {
	mi := &file_proto_export_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logbook.ProtoReflect.Descriptor instead.
func (*Logbook) Descriptor() ([]byte, []int) {
	return file_proto_export_proto_rawDescGZIP(), []int{4}
}

func (x *Logbook) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *Logbook) GetLogbookId() string {
	if x != nil {
		return x.LogbookId
	}
	return ""
}

type LogbookEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        uint64                 `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	LogbookId     uint64                 `protobuf:"varint,2,opt,name=logbook_id,json=logbookId,proto3" json:"logbook_id,omitempty"`
	Bottom        string                 `protobuf:"bytes,3,opt,name=bottom,proto3" json:"bottom,omitempty"`
	CloudCover    string                 `protobuf:"bytes,4,opt,name=cloud_cover,json=cloudCover,proto3" json:"cloud_cover,omitempty"`
	Depth         string                 `protobuf:"bytes,5,opt,name=depth,proto3" json:"depth,omitempty"`
	DepthUnit     string                 `protobuf:"bytes,6,opt,name=depth_unit,json=depthUnit,proto3" json:"depth_unit,omitempty"`
	EntryDate     string                 `protobuf:"bytes,7,opt,name=entry_date,json=entryDate,proto3" json:"entry_date,omitempty"`
	Landmark      string                 `protobuf:"bytes,8,opt,name=landmark,proto3" json:"landmark,omitempty"`
	Latitude      string                 `protobuf:"bytes,9,opt,name=latitude,proto3" json:"latitude,omitempty"`
	LocalTime     string                 `protobuf:"bytes,10,opt,name=local_time,json=localTime,proto3" json:"local_time,omitempty"`
	Longitude     string                 `protobuf:"bytes,11,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Page          string                 `protobuf:"bytes,12,opt,name=page,proto3" json:"page,omitempty"`
	SeaState      string                 `protobuf:"bytes,13,opt,name=sea_state,json=seaState,proto3" json:"sea_state,omitempty"`
	ShipHeading   string                 `protobuf:"bytes,14,opt,name=ship_heading,json=shipHeading,proto3" json:"ship_heading,omitempty"`
	ShipSightings string                 `protobuf:"bytes,15,opt,name=ship_sightings,json=shipSightings,proto3" json:"ship_sightings,omitempty"`
	Weather       string                 `protobuf:"bytes,16,opt,name=weather,proto3" json:"weather,omitempty"`
	WindDirection string                 `protobuf:"bytes,17,opt,name=wind_direction,json=windDirection,proto3" json:"wind_direction,omitempty"`
	WindForce     string                 `protobuf:"bytes,18,opt,name=wind_force,json=windForce,proto3" json:"wind_force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogbookEntry) Reset() {
	*x = LogbookEntry{}
	mi := &file_proto_export_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogbookEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogbookEntry) ProtoMessage() {}

func (x *LogbookEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_export_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogbookEntry.ProtoReflect.Descriptor instead.
func (*LogbookEntry) Descriptor() ([]byte, []int) {
	return file_proto_export_proto_rawDescGZIP(), []int{5}
}

func (x *LogbookEntry) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *LogbookEntry) GetLogbookId() uint64 {
	if x != nil {
		return x.LogbookId
	}
	return 0
}

func (x *LogbookEntry) GetBottom() string {
	if x != nil {
		return x.Bottom
	}
	return ""
}

func (x *LogbookEntry) GetCloudCover() string {
	if x != nil {
		return x.CloudCover
	}
	return ""
}

func (x *LogbookEntry) GetDepth() string {
	if x != nil {
		return x.Depth
	}
	return ""
}

func (x *LogbookEntry) GetDepthUnit() string {
	if x != nil {
		return x.DepthUnit
	}
	return ""
}

func (x *LogbookEntry) GetEntryDate() string {
	if x != nil {
		return x.EntryDate
	}
	return ""
}

func (x *LogbookEntry) GetLandmark() string {
	if x != nil {
		return x.Landmark
	}
	return ""
}

func (x *LogbookEntry) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

func (x *LogbookEntry) GetLocalTime() string {
	if x != nil {
		return x.LocalTime
	}
	return ""
}

func (x *LogbookEntry) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

func (x *LogbookEntry) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *LogbookEntry) GetSeaState() string {
	if x != nil {
		return x.SeaState
	}
	return ""
}

func (x *LogbookEntry) GetShipHeading() string {
	if x != nil {
		return x.ShipHeading
	}
	return ""
}

func (x *LogbookEntry) GetShipSightings() string {
	if x != nil {
		return x.ShipSightings
	}
	return ""
}

func (x *LogbookEntry) GetWeather() string {
	if x != nil {
		return x.Weather
	}
	return ""
}

func (x *LogbookEntry) GetWindDirection() string {
	if x != nil {
		return x.WindDirection
	}
	return ""
}

func (x *LogbookEntry) GetWindForce() string {
	if x != nil {
		return x.WindForce
	}
	return ""
}

var File_proto_export_proto protoreflect.FileDescriptor

const file_proto_export_proto_rawDesc = "" +
	"\n" +
	"\x12proto/export.proto\x12\x11ewhales.export.v1\"\x93\x01\n" +
	"\rExportRequest\x12?\n" +
	"\bmetadata\x18\x01 \x01(\v2!.ewhales.export.v1.ExportMetadataH\x00R\bmetadata\x126\n" +
	"\x05batch\x18\x02 \x01(\v2\x1e.ewhales.export.v1.ExportBatchH\x00R\x05batchB\t\n" +
	"\apayload\"h\n" +
	"\x0eExportMetadata\x12+\n" +
	"\x11expected_logbooks\x18\x01 \x01(\x03R\x10expectedLogbooks\x12)\n" +
	"\x10expected_entries\x18\x02 \x01(\x03R\x0fexpectedEntries\"\x80\x01\n" +
	"\vExportBatch\x126\n" +
	"\blogbooks\x18\x01 \x03(\v2\x1a.ewhales.export.v1.LogbookR\blogbooks\x129\n" +
	"\aentries\x18\x02 \x03(\v2\x1f.ewhales.export.v1.LogbookEntryR\aentries\"D\n" +
	"\x0eExportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\aLogbook\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x04R\x06postId\x12\x1d\n" +
	"\n" +
	"logbook_id\x18\x02 \x01(\tR\tlogbookId\"\xa3\x04\n" +
	"\fLogbookEntry\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x04R\x06postId\x12\x1d\n" +
	"\n" +
	"logbook_id\x18\x02 \x01(\x04R\tlogbookId\x12\x16\n" +
	"\x06bottom\x18\x03 \x01(\tR\x06bottom\x12\x1f\n" +
	"\vcloud_cover\x18\x04 \x01(\tR\n" +
	"cloudCover\x12\x14\n" +
	"\x05depth\x18\x05 \x01(\tR\x05depth\x12\x1d\n" +
	"\n" +
	"depth_unit\x18\x06 \x01(\tR\tdepthUnit\x12\x1d\n" +
	"\n" +
	"entry_date\x18\a \x01(\tR\tentryDate\x12\x1a\n" +
	"\blandmark\x18\b \x01(\tR\blandmark\x12\x1a\n" +
	"\blatitude\x18\t \x01(\tR\blatitude\x12\x1d\n" +
	"\n" +
	"local_time\x18\n" +
	" \x01(\tR\tlocalTime\x12\x1c\n" +
	"\tlongitude\x18\v \x01(\tR\tlongitude\x12\x12\n" +
	"\x04page\x18\f \x01(\tR\x04page\x12\x1b\n" +
	"\tsea_state\x18\r \x01(\tR\bseaState\x12!\n" +
	"\fship_heading\x18\x0e \x01(\tR\vshipHeading\x12%\n" +
	"\x0eship_sightings\x18\x0f \x01(\tR\rshipSightings\x12\x18\n" +
	"\aweather\x18\x10 \x01(\tR\aweather\x12%\n" +
	"\x0ewind_direction\x18\x11 \x01(\tR\rwindDirection\x12\x1d\n" +
	"\n" +
	"wind_force\x18\x12 \x01(\tR\twindForce2f\n" +
	"\x0fExporterService\x12S\n" +
	"\n" +
	"ExportData\x12 .ewhales.export.v1.ExportRequest\x1a!.ewhales.export.v1.ExportResponse(\x01B3Z1github.com/agl/ewhales-v1-exporter/proto;exportpbb\x06proto3"

var (
	file_proto_export_proto_rawDescOnce sync.Once
	file_proto_export_proto_rawDescData []byte
)

func file_proto_export_proto_rawDescGZIP() []byte {
	file_proto_export_proto_rawDescOnce.Do(func() {
		file_proto_export_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_export_proto_rawDesc), len(file_proto_export_proto_rawDesc)))
	})
	return file_proto_export_proto_rawDescData
}

var file_proto_export_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_export_proto_goTypes = []any{
	(*ExportRequest)(nil),  // 0: ewhales.export.v1.ExportRequest
	(*ExportMetadata)(nil), // 1: ewhales.export.v1.ExportMetadata
	(*ExportBatch)(nil),    // 2: ewhales.export.v1.ExportBatch
	(*ExportResponse)(nil), // 3: ewhales.export.v1.ExportResponse
	(*Logbook)(nil),        // 4: ewhales.export.v1.Logbook
	(*LogbookEntry)(nil),   // 5: ewhales.export.v1.LogbookEntry
}
var file_proto_export_proto_depIdxs = []int32{
	1, // 0: ewhales.export.v1.ExportRequest.metadata:type_name -> ewhales.export.v1.ExportMetadata
	2, // 1: ewhales.export.v1.ExportRequest.batch:type_name -> ewhales.export.v1.ExportBatch
	4, // 2: ewhales.export.v1.ExportBatch.logbooks:type_name -> ewhales.export.v1.Logbook
	5, // 3: ewhales.export.v1.ExportBatch.entries:type_name -> ewhales.export.v1.LogbookEntry
	0, // 4: ewhales.export.v1.ExporterService.ExportData:input_type -> ewhales.export.v1.ExportRequest
	3, // 5: ewhales.export.v1.ExporterService.ExportData:output_type -> ewhales.export.v1.ExportResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_export_proto_init() }
func file_proto_export_proto_init() {
	if File_proto_export_proto != nil {
		return
	}
	file_proto_export_proto_msgTypes[0].OneofWrappers = []any{
		(*ExportRequest_Metadata)(nil),
		(*ExportRequest_Batch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_export_proto_rawDesc), len(file_proto_export_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_export_proto_goTypes,
		DependencyIndexes: file_proto_export_proto_depIdxs,
		MessageInfos:      file_proto_export_proto_msgTypes,
	}.Build()
	File_proto_export_proto = out.File
	file_proto_export_proto_goTypes = nil
	file_proto_export_proto_depIdxs = nil
}
